services:
  bookhound:
    build:
      context: .
      dockerfile: Dockerfile.bookhound
    image: mcr.microsoft.com/dotnet/sdk:10.0.101-noble-amd64
    container_name: bookhound-dotnet-build
    hostname: bh-app
    # best for adb debugging inside the container
    network_mode: host

    volumes:
      - .:/workspaces/BookHound
      - apkshare:/apkshare
      
    working_dir: /workspaces/BookHound
    command:
      sleep infinity

  emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android-emulator
    hostname: bh-emu
    privileged: true
    environment:
      - DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm
    volumes:
      - apkshare:/apkshare
    ports:
      - "5554:5554"   # Emulator console
      - "5555:5555"   # ADB
      - "6080:6080"   # VNC
    command: /bin/bash -c "start-emulator"

volumes:
  apkshare: