services:
  bookhound:
    image: mcr.microsoft.com/dotnet/sdk:10.0.101-alpine3.23-amd64
    container_name: bookhound-dotnet-build
    volumes:
      - .:/workspaces/bookhound
      - apkshare:/apkshare
    working_dir: /workspaces/bookhound/BookHoundApp
    command: sleep infinity

  emulator:
    image: budtmo/docker-android:emulator_14.0
    container_name: android-emulator
    privileged: true
    environment:
      - DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm
    volumes:
      - apkshare:/apkshare
    ports:
      - "5554:5554"   # Emulator console
      - "5555:5555"   # ADB
      - "6080:6080"   # VNC
    command: /bin/bash -c "start-emulator"

volumes:
  apkshare: